"""
ImagePromptGenerator - Generates contextual image prompts based on video script using AI
"""

import json
from openai import OpenAI
from config import Config


class ImagePromptGenerator:
    """Generates story-specific image prompts using OpenAI with structured outputs"""

    def __init__(self, api_key=None):
        self.api_key = api_key or Config.OPENAI_API_KEY
        self.client = OpenAI(api_key=self.api_key)

    def generate_prompts(self, subject, script, count=10, prompt_config=None, sentences=None):
        """
        Generate AI-powered image prompts that follow the story

        Args:
            subject: The video subject (e.g., "Phoenix Lights 1997", "2020 Toyota Supra")
            script: The full video script (~250 words)
            count: Number of image prompts to generate (default: 10)
            prompt_config: PromptConfig object with custom instructions
            sentences: List of individual sentences for 1:1 mapping (optional)

        Returns:
            list: List of dicts with 'prompt', 'description', 'name' keys
        """
        # Build the prompt for OpenAI
        system_prompt = self._build_system_prompt(count, prompt_config, sentences)
        user_prompt = self._build_user_prompt(subject, script, count, sentences)

        try:
            # Use structured outputs for reliable JSON parsing
            response = self.client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=1.2,  # Creative but not too wild
                max_tokens=2000,
                response_format={"type": "json_object"}
            )

            # Parse the JSON response
            result = json.loads(response.choices[0].message.content)

            # Extract prompts array
            if "prompts" not in result:
                raise ValueError("Response missing 'prompts' field")

            prompts = result["prompts"]

            # Validate we got the right number
            if len(prompts) < count:
                print(f"⚠️  Warning: Only got {len(prompts)}/{count} prompts from AI")

            # Format for consistency with template-based system
            formatted_prompts = []
            for i, prompt_data in enumerate(prompts[:count]):
                formatted_prompts.append({
                    "prompt": prompt_data.get("prompt", ""),
                    "description": prompt_data.get("description", f"Scene {i+1}"),
                    "name": f"ai_scene_{i+1}"
                })

            return formatted_prompts

        except Exception as e:
            print(f"✗ Failed to generate AI prompts: {e}")
            # Return empty list - caller should fall back to templates
            return []

    def _build_system_prompt(self, count, prompt_config, sentences=None):
        """Build the system prompt for AI image generation"""

        # Get custom instructions from config if available
        if prompt_config:
            custom_instructions = prompt_config.get_ai_prompt_instructions()
            if custom_instructions:
                return custom_instructions

        # Sentence-level mapping mode
        if sentences:
            return f"""You are an expert at creating photorealistic image prompts for AI image generation.

Your task: Generate EXACTLY {count} diverse, cinematic image prompts that match 1:1 with each sentence in the script.

CRITICAL RULES FOR SENTENCE-LEVEL MAPPING WITH CONTEXT:
1. Generate EXACTLY {count} prompts (one for each sentence)
2. READ THE FULL STORY first to understand all context, characters, objects, and narrative
3. Use the full story context to resolve pronouns and references (e.g., "it" = the acorn-shaped UFO mentioned earlier)
4. Each prompt must visually represent the content/mood of its corresponding sentence WITH full story knowledge
5. Each prompt must be ONE SENTENCE describing a specific, concrete scene or visual
6. Maintain VISUAL CONTINUITY - objects, characters, settings should be consistent across prompts
7. Prompts should FOLLOW THE STORY'S NARRATIVE ARC naturally
8. Include VARIETY: wide shots, close-ups, atmospheric scenes, action moments, perspectives
9. Be SPECIFIC and DETAILED using information from the full story (not generic)
10. Focus on VISUAL ELEMENTS that can be generated by AI (no text, logos, or specific faces)
11. Make prompts CINEMATIC and engaging
12. Stay true to the subject and tone of the story

KEY: When a sentence has pronouns or references (it, they, the object, the site, etc.),
look at the FULL STORY to understand what they mean and describe the actual thing in your prompt.

OUTPUT FORMAT:
Return a JSON object with this exact structure:
{{
  "prompts": [
    {{"prompt": "detailed one-sentence description with full context", "description": "Sentence 1"}},
    {{"prompt": "another detailed description resolving all references", "description": "Sentence 2"}},
    ...{count} total prompts
  ]
}}

Example prompt styles:
- "Wide establishing shot of Phoenix Arizona skyline at dusk with clear evening sky"
- "Massive V-shaped formation of mysterious lights hovering silently over urban area"
- "Close-up of awestruck witness face illuminated by bright light from above"
- "Metallic acorn-shaped UFO object with glowing surface resting in dense forest clearing"
"""

        # Default instructions (non-sentence mode)
        return f"""You are an expert at creating photorealistic image prompts for AI image generation.

Your task: Generate {count} diverse, cinematic image prompts that visually tell the story.

CRITICAL RULES:
1. Each prompt must be ONE SENTENCE describing a specific scene or visual
2. Prompts should FOLLOW THE STORY'S NARRATIVE ARC (beginning → middle → end)
3. Include VARIETY: wide shots, close-ups, atmospheric scenes, action moments, character perspectives
4. Be SPECIFIC and DETAILED (not generic)
5. Focus on VISUAL ELEMENTS that can be generated by AI (no text, logos, or specific faces)
6. Make prompts CINEMATIC and engaging
7. Stay true to the subject and tone of the story

OUTPUT FORMAT:
Return a JSON object with this exact structure:
{{
  "prompts": [
    {{"prompt": "detailed one-sentence description", "description": "short label like 'Opening scene'"}},
    {{"prompt": "another detailed description", "description": "label"}},
    ...
  ]
}}

Example prompt styles:
- "Wide establishing shot of Phoenix Arizona skyline at dusk with clear evening sky"
- "Massive V-shaped formation of mysterious lights hovering silently over urban area"
- "Close-up of awestruck witness face illuminated by bright light from above"
"""

    def _build_user_prompt(self, subject, script, count, sentences=None):
        """Build the user prompt with subject and script"""

        if sentences:
            # Sentence-level mapping mode with full context
            sentences_formatted = "\n".join([f"{i+1}. {s}" for i, s in enumerate(sentences)])
            return f"""SUBJECT: {subject}

FULL STORY (for context and understanding):
{script}

---

SENTENCES TO VISUALIZE (1:1 mapping required):
{sentences_formatted}

---

Generate EXACTLY {count} photorealistic image prompts that match 1:1 with each sentence.

CRITICAL INSTRUCTIONS:
- READ THE FULL STORY to understand context, characters, objects, and narrative flow
- Prompt 1 should visually represent Sentence 1 (with full story context)
- Prompt 2 should visually represent Sentence 2 (understanding pronouns like "it", "the object", etc.)
- And so on... EXACTLY {count} prompts total
- When you see pronouns (it, they, the object, etc.), use the FULL STORY to understand what they refer to
- Each prompt = ONE SENTENCE describing a specific, concrete visual scene
- Make prompts cinematic, specific, and detailed
- Maintain visual continuity across the narrative

EXAMPLE:
If Sentence 3 says "The object was metallic" and the full story mentions "acorn-shaped UFO",
your prompt should describe: "Metallic acorn-shaped UFO object..."

Return as JSON with "prompts" array containing exactly {count} prompts."""

        # Default mode (no sentence mapping)
        return f"""SUBJECT: {subject}

VIDEO SCRIPT:
{script}

---

Generate {count} photorealistic image prompts that visually tell this story from beginning to end.

Remember:
- Each prompt = ONE SENTENCE
- Follow the story's narrative arc
- Include variety of shot types and angles
- Be specific and detailed
- Make them cinematic

Return as JSON with "prompts" array."""
